# Generated by Django 2.2 on 2019-05-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190419_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=32)),
                ('img', models.FileField(upload_to='portfolio')),
                ('text', models.TextField(default='', max_length=2048)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_list', to='web.Block')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
