# Generated by Django 2.2 on 2019-06-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_contactform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
