# Generated by Django 2.2 on 2019-06-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20190606_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='comment',
            field=models.TextField(default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
